### ISSUE TITLE
Redesign MeldR

### ISSUE THREAD

**Issue by Wouterboer** [forza-mor-rotterdam/frontend#24]

**Comment by peterboer** [comment]
@Wouterboer  is deze nog actief? want zo ja: kan je hiervan de repository wijzigen naar profilr? we werken niet meer met 'frontend'/'backend' en ik kan dit niet wijzigen.

**Comment by peterboer** [comment]
Afgesloten omdat grote werk gedaan is. Nieuwe ontwikkelingen nemen we op in additionele stories.
